config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/mes-réservations", to: "bookings#index", as: :mes_reservations
  get "/bookings/:id/checkout/paiement", to: "bookings#paiement", as: :paiement
  get "users/dashboard", to: "pages#dashboard"
  get "users/informations", to: "pages#informations"
  resources :bookings, only: %i[new create show] do
    member do
      get :checkout
    end
  end
  get "/objects", to: "celestial_bodies#index", as: :objects

  resources :observation_plannings, only: %i[index show]
end

app/models/observation_planning.rb
require "json"
require "httparty"
require "tzinfo"
require "timezone"
require "date"

class ObservationPlanning < ApplicationRecord
  belongs_to :user
  has_many :targets

  has_many :celestial_bodies, through: :targets

  serialize :visible_objects, JSON

  validates :name, presence: true
  validates_time :start_time, presence: true
  validates_time :end_time, after: :start_time, presence: true

  # Convert a decimal number representing hours to hours, minutes, and seconds
  def decimal_to_hms(decimal)
    hours = decimal.to_i
    minutes = ((decimal - hours) * 60).to_i
    seconds = (((decimal - hours) * 60) - minutes) * 60
    return hours, minutes, seconds
  end

  # Retourne le décalage horaire en heure entre l'heure locale et l'heure UTC pour la position de l'observateur
  def utc_offset
    coordinates = [user.latitude, user.longitude]
    # find the user last booking date
    date = user.bookings.last.date

    timezone = Timezone.lookup(*coordinates)

    if timezone
      tz = TZInfo::Timezone.get(timezone.name)
      offset_seconds = tz.period_for_local(date).utc_total_offset # Récupère l'offset en secondes
      offset_hours = offset_seconds / 3600.0 # Convertit les secondes en heures
    else
      offset_hours = 0 # Utilise UTC par défaut si le fuseau horaire ne peut pas être déterminé
    end

    offset_hours
  end


  # Find astronomical objects visible above the horizon from the observer's location at a given time
  def select_objects
    observer_latitude = user.latitude # Latitude of observer in decimal degrees
    observer_longitude = user.longitude # Longitude of observer in decimal degrees
    observation_start_utc = start_time - utc_offset.hours # Start time of observation in UTC
    lst = local_sidereal_time(observer_longitude, observation_start_utc) # Local sidereal time at start of observation
    objects = load_objects_from_file('db/catalogue-de-messier.json') # Load astronomical objects from a file
    selected_objects = [] # Initialize an empty array to store visible objects

    # For each object, calculate its altitude and azimuth and add it to the selected_objects array if it is visible
    objects.each do |object|
      ra, dec = parse_ra_and_dec(object) # Extract right ascension and declination from object data
      altitude, azimuth = calculate_altitude_and_azimuth(ra, dec, lst, observer_latitude, observer_longitude) # Calculate altitude and azimuth of object at start of observation

      if altitude > 20 # If the object is above the horizon, add it to the selected_objects array with its altitude and azimuth
        selected_objects << object.merge(altitude: altitude, azimuth: azimuth)
      end
    end
    # Trie selected_objects par ordre décroissant de leur altitude
    sorted_objects = selected_objects.sort_by { |obj| -obj[:altitude] }
    # Sauvegarde les objets visibles dans la base de données
    self.visible_objects = sorted_objects.to_json

    return sorted_objects # Return the array of visible objects
  end

  # Calculate the local sidereal time at a given location and time
  def local_sidereal_time(observer_longitude, observation_start_utc)
    j2000 = Time.utc(2000, 1, 1, 12, 0, 0).to_i # Julian date of J2000.0 epoch
    days_since_j2000 = (observation_start_utc.to_f - j2000) / 86_400 # Number of days since J2000.0 epoch
    (100.46 + (0.985647 * days_since_j2000) + observer_longitude + (15 * utc_offset)) % 360 # Calculate the local sidereal time in degrees
  end

  # Load astronomical objects from a JSON file
  def load_objects_from_file(file_path)
    json_file = File.read(file_path) # Read the contents of the file as a string
    JSON.parse(json_file) # Parse the string as a JSON object
  end

  # Convert right ascension and declination from hours/degrees, minutes, and seconds to decimal degrees
  def parse_ra_and_dec(object)
    ra_hours, ra_minutes, ra_seconds = object['ra'].split(':').map(&:to_f) # Split right ascension into hours, minutes, and seconds
    ra = (hms_to_decimal(ra_hours, ra_minutes, ra_seconds) * 360) / 24 # Convert right ascension to decimal degrees
    dec_degrees, dec_minutes, dec_seconds = object['dec'].split(':').map(&:to_f) # Split declination into degrees, minutes, and seconds
    dec = dec_degrees + (dec_minutes / 60.0) + (dec_seconds / 3600.0) # Convert declination to decimal degrees

    return ra, dec
  end

  # Calculate object's altitude and azimuth at a given time and location
  def calculate_altitude_and_azimuth(ra, dec, lst, observer_latitude, _observer_longitude)
    ra_rad = ra * Math::PI / 180
    dec_rad = dec * Math::PI / 180
    lst_rad = lst * Math::PI / 180
    observer_latitude_rad = observer_latitude * Math::PI / 180

    object_altitude = Math.asin((Math.sin(dec_rad) * Math.sin(observer_latitude_rad)) + (Math.cos(dec_rad) * Math.cos(observer_latitude_rad) * Math.cos(lst_rad - ra_rad)))
    object_azimuth = Math.atan2(-Math.sin(lst_rad - ra_rad), (Math.tan(observer_latitude_rad) * Math.cos(dec_rad)) - (Math.sin(dec_rad) * Math.cos(lst_rad - ra_rad)))

    azimuth = ((object_azimuth * 180 / Math::PI) + 360) % 360 # Convert azimuth from radians to degrees
    altitude = object_altitude * 180 / Math::PI # Convert altitude from radians to degrees

    return altitude, azimuth
  end

  # Convert hours, minutes, and seconds to decimal hours
  def hms_to_decimal(hours, minutes, seconds)
    decimal = hours + (minutes / 60.0) + (seconds / 3600.0)
    return decimal
  end

  # call api to get sunrise and sunset infos for the latitude and longitude of User
  # and the date of the observation
  # date in format YYYY-MM-DD
  def sun(date)
    latitude = user.latitude
    longitude = user.longitude
    api_url = "https://api.sunrise-sunset.org/json?lat=#{latitude}&lng=#{longitude}&date=#{date}"

    response = HTTParty.get(api_url)
    json = JSON.parse(response.body)

    unformated_rise = DateTime.strptime(json['results']['nautical_twilight_begin'], "%H:%M:%S").to_time.utc
    local_sunrise = (unformated_rise + utc_offset.hours).strftime('%H:%M')
    unformated_set = DateTime.strptime(json['results']['nautical_twilight_end'], "%H:%M:%S").to_time.utc
    local_sunset = (unformated_set + utc_offset.hours).strftime('%H:%M')

    if local_sunrise.to_i > 12
      local_sunrise = (unformated_rise + utc_offset.hours - 12.hours).strftime('%H:%M')
    end

    if local_sunset.to_i < 12
      local_sunset = (unformated_set + utc_offset.hours + 12.hours).strftime('%H:%M')
    end

    self.sunrise = local_sunrise
    self.sunset = local_sunset
  end



  # call the api to get the moon phase for the date of the observation and rise/set time for user location
  def moon(date)
    application_id = '680ddb64-a69a-49e0-b03e-36b96b212227'
    application_secret = 'b847e997f20db4ddf0a840643c139a9e0145ba6e2c81888e27643657f7cde0132c1a11c79858fcd6611091705821e6058d8090656f992ce31bd29f2edd05416d6ff1e3405d89c1b12106db4b96c8dcd62fd37ab2eeb13ea47b82b2892d24c3ea185abd9aa1d7d7eeb0b82936c2e3a147'

    credentials = "#{application_id}:#{application_secret}"
    hash = Base64.strict_encode64(credentials)

    headers = {
      'Authorization' => "Basic #{hash}",
      'Content-Type' => 'application/json'
    }
    body = {
      format: 'svg',
      style: {
        moonStyle: 'default',
        backgroundStyle: 'stars',
        backgroundColor: 'black',
        headingColor: 'white',
        textColor: 'white'
      },
      observer: {
        latitude: user.latitude,
        longitude: user.longitude,
        date: date
      },
      view: {
        type: 'landscape-simple',
        orientation: 'north-up'
      }
    }
    response = HTTParty.post('https://api.astronomyapi.com/api/v2/studio/moon-phase', headers: headers, body: body.to_json)
    moon_phase_url = JSON.parse(response.body)['data']['imageUrl']
    self.moon_phase = moon_phase_url
  end
end

app/controllers/observation_plannings_controller.rb
class ObservationPlanningsController < ApplicationController
  def index
    @observation_plannings = current_user.observation_plannings.sort_by(&:start_time)
  end

  def show
    @observation_planning = ObservationPlanning.find(params[:id])
    @visible_objects = JSON.parse(@observation_planning.visible_objects)
  end
end

app/views/observation_plannings/index.html.erb
<%# Display all the observation plannings %>
<div class= "container-fluid">
  <div class="titre m-3">
    <h2 class="text-shadow" style="font-size: 3rem"> MES PLANNINGS </h2>
  </div>
  <div class= "d-flex flex-column align-self-center">
    <div class= "col-md-5 mx-auto">
      <div>
        <% @observation_plannings.each do |observation_planning| %>
          <div class="card-paiement px-4">
            <p>
              <div class="row">
                <strong><%= "#{observation_planning.name} pour #{observation_planning.user.first_name} à #{observation_planning.location}" %></strong>
              </div>
              <div class="row">
                <p><%= "De #{observation_planning.start_time.strftime("%H:%M")} à #{observation_planning.end_time.strftime("%H:%M")}" %></p>
              </div>
            </p>
            <%# Display the link to show the observation planning details %>
            <div class="row" style="padding: 0px">
              <%= link_to "Afficher le planning", observation_planning_path(observation_planning), class: "btn-straight px-2 ", style: "font-size:0.9rem; height: 40px" %>
              <a href="#" class="btn-straight px-2 " style="font-size:0.9rem; height: 40px">Modifier</a>
              <a href="#" class="btn-straight px-2 " style="font-size:0.9rem; height: 40px">Supprimer</a>
            </div>
          </div>
        <% end %>
        <div class="row mt-4 mb-4">
          <button class="btn-straight">Créer un nouveau planning</button>
        </div>
      </div>
    </div>
  </div>

app/views/observation_plannings/show.html.erb
<div class= "container-fluid" data-controller="observation pointage">
  <div class="titre m-3" >
    <h2 class="text-shadow" style="font-size: 2rem"> <%= "#{@observation_planning.name.upcase} POUR #{@observation_planning.user.first_name.upcase}" %></h2>
    <h3 class="text-shadow" style="font-size: 1.5rem"><%= "À #{@observation_planning.location.upcase}" %></h3>
    <h3 class="text-shadow" style="font-size: 1.5rem"><%= "DE #{@observation_planning.start_time.strftime("%H:%M")} À #{@observation_planning.end_time.strftime("%H:%M")}" %></h3>
  </div>
  <div class="sunmoon col-12 d-flex flex-row justify-content-center  mb-3">
    <%#display the image moonphasels.png in the folder db/images/sunmoon/%>
    <div class = "col-6 m-1 col-lg-5">
      <img src="<%= @observation_planning.moon_phase %>" alt="Phase de la lune" class="sunmoonimg">
    </div>
    <div class = "col-6 m-1 col-lg-5">
      <div class = "sun-card d-flex flex-row">
        <div class="col-6">
          <%= image_tag"Sun.png"%>
        </div>
        <div class="col-6">
          <h4>Soleil</h4>
          <div class ="mt-3">
            <p>Lever: <%= @observation_planning.sunrise %></p>
            <p>Coucher: <%= @observation_planning.sunset%> </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <h2> Proposition d'objets célestes à observer</h2>
  <%# Display all the celestial bodies of the observation planning%>
  <% heure_observation = @observation_planning.start_time %>
  <% @observation_planning.celestial_bodies.each do |celestial_body| %>
    <div class="observation-plan-card col-12 col-lg-8 d-flex flex-row mb-4 mx-auto">
      <div class="col-4 col-lg-4" style="position:relative">
        <%= cl_image_tag celestial_body.photo.key, class:"image"%>
        <h3><%= "#{celestial_body.name}" %></h3>
      </div>
      <div class="observation-plan-card-infos col-6 col-lg-4 py-2" data-target="observation.description">
        <div class="texte px-1">
          <div class="d-flex flex-row  align-items-center">
            <i class="fa-regular fa-eye"></i>
            <p><strong>Observer à :</strong> <%= "#{(heure_observation + 15.minutes).strftime("%H:%M")}" %></p>
          </div>
          <div class="d-flex flex-row  align-items-center">
            <%= image_tag "azimuth.png",  width:'20', height:'20'%>
            <p><strong>Azimuth: </strong><%= @visible_objects.find {|f| f['messier'] == celestial_body.name}['azimuth'].round %>°</p>
          </div>
          <div class="d-flex flex-row  align-items-center">
            <i class="fa-solid fa-arrow-up px-1"></i>
            <p><strong>Altitude:</strong> <%= @visible_objects.find {|f| f['messier'] == celestial_body.name}['altitude'].round%>°</p>
          </div>
          <div class="d-flex flex-row  align-items-center">
            <i class="fa-regular fa-compass px-1"></i>
            <p><strong>Orientation:</strong> <%= CelestialBody.orientation(@visible_objects.find {|f| f['messier'] == celestial_body.name}['azimuth']) %></p>
          </div>
          <div class="description" data-observation-target="description">
            <p><%= celestial_body.description %></p>
          </div>
        </div>
      </div>
      <div class="col-2 col-lg-2 d-flex align-items-center justify-content-center">
        <div class="col-2 d-flex flex-column">
          <i class="fa-solid fa-circle-info px-1 mb-4" data-action="click->observation#toggleDescription"></i>
          <%= image_tag "target.png",  width:'25', height:'25', data: { celestial_body_name: celestial_body.name, action: "click->pointage#pointTelescope", pointage_celestial_body_name: celestial_body.name } %>
        </div>
      </div>
    </div>
    <% heure_observation += 15.minutes %>
  <% end %>
</div>