config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/mes-réservations", to: "bookings#index", as: :mes_reservations
  get "/bookings/:id/checkout/paiement", to: "bookings#paiement", as: :paiement
  get "users/dashboard", to: "pages#dashboard"
  get "users/informations", to: "pages#informations"
  resources :bookings, only: %i[new create show] do
    member do
      get :checkout
    end
  end
  get "/objects", to: "celestial_bodies#index", as: :objects

  resources :observation_plannings, only: %i[index show]
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :zip, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :price, presence: true, numericality: true
  validates :date, presence: true
  validates :status, presence: true
  enum status: { attente: 0, confirmé: 1, annulé: 2 }

  belongs_to :user
  has_many :booking_items
  has_many :items, through: :booking_items

  before_validation :calculate_price
  after_create :generate_observation_planning

  # create a new observation planning for each new booking
  def generate_observation_planning
    planning = ObservationPlanning.new
    # add the booking user_id to the observation planning
    planning.user_id = user_id
    # add the booking location to the observation planning
    planning.location = city
    # call the sun method from the observation planning model to get the sunries and sunset time
    planning.sun(date.strftime("%y-%m-%d"))
    # the booking date is the observation planning date and start time is 20:00 and end time is 22:00
    planning.start_time = date + 20.hours
    planning.end_time = date + 22.hours
    planning.name = "Plan d'observation du #{date.strftime("%d.%m.%y")}"
    # add 8 celestial bodies to the observation planning, wich are the 8 first celestial bodies corresponding
    # to the ones returned by the visible_objects method
    planning.select_objects # call the select_objects method from the observation planning model
    planning.celestial_bodies = JSON.parse(planning.visible_objects).first(8).map { |object| CelestialBody.find_by!(name: object["messier"]) }
    # call the moon method from the observation planning model to get the moon_phase image url
    planning.moon(date.strftime("%Y-%m-%d"))
    planning.save
  end

  private

  def calculate_price
    self.price = items.sum(&:price)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_items, only: %i[new create]

  def index
    @bookings = Booking.where(user: current_user)
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.status = :attente
    @booking.user.street = @booking.street
    @booking.user.city = @booking.city
    @booking.user.zip = @booking.zip
    @booking.user.save
    if @booking.save
      redirect_to checkout_booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def checkout
    @booking = Booking.find(params[:id])
  end

  def paiement
    @observation_planning = current_user.observation_plannings.last
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :street, :city, :zip, item_ids: [])
  end

  def set_items
    @items = Item.all
  end
end

app/views/bookings/_booking_options.html.erb
<div class="container">
  <div class="row" style="border-bottom: solid">
    <div class="col-4">
      <p><%= item.name %></p>
    </div>
    <div class="col-8 text-end">
      <p><%= item.price %> CHF</p>
    </div>
  </div>
</div>

app/views/bookings/checkout.html.erb
<div class="container-fluid mt-5">
    <h1 class="text-shadow" style="font-size: 2rem">CONFIRMER LA RESERVATION</h1>
    <h3>Vérifiez les informations de réservation avant de procéder au paiement</h3>
  <div class="checkout-card col-md-10 mx-auto">
    <div class="row">
      <h2>Informations de facturation</h2>
      <div class="col-4">
        <p><strong>Nom:</strong></p>
      </div>
      <div class="col-8">
        <p><%= "#{current_user.first_name} #{current_user.last_name}" %> </p>
      </div>
    </div>
    <div class="row">
      <div class="col-4">
        <p><strong>Adresse:</strong></p>
      </div>
      <div class="col-8">
        <p> <%= "#{current_user.street} #{current_user.zip} #{current_user.city}"  %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-4">
        <p><strong>Mail:</strong></p>
      </div>
      <div class="col-8">
        <p class=""> <%= current_user.email %></p>
      </div>
    </div>
  </div>
  <div>
    <div class="row checkout-card col-md-10 mx-auto">
      <h2>Détails de la réservation</h2>
      <% @booking.items.each do |item|%>
        <%= render "booking_options", item: %>
      <% end %>
      <div>
        <p style="text-align: right"><strong>Total <%= @booking.price %> CHF</strong></p>
      </div>
    </div>
    <div class="mb-2">
      <%= link_to "Procéder au paiement", paiement_path, class: "btn-straight"%>
    </div>
    <div class="row text-center">
      <a href="#" style="color: white; font-size: 1rem">Retour</a>
    </div>

  </div>
</div>

app/views/bookings/index.html.erb
<div class="container-fluid">
  <div class="row mt-4 mb-4">
  <h2 class="text-shadow" style="font-size: 3rem"> MES RESERVATIONS </h2>
</div>
<div class="container justify-content-center">
  <% @bookings.each do |booking| %>
    <%# display only the bookings for the current user if there is any bookings%>
    <% if booking.user_id == current_user.id %>
      <div class="row checkout-card col-md-10 mx-auto">
        <div class= "card-booking-info">
          <div class="row">
            <div class="col-4">
              <p><strong>Date:</strong> <%= booking.date.strftime("%d.%m.%y") %></p>
            </div>
            <div class="col-8 text-end">
              <span class="card-booking-status">
                <% booking.status = :confirmé %>
                <%= booking.status %>
              </span>
            </div>
          </div>
          <p><strong>Adresse de livraison: </strong></p>
          <p><%="#{booking.street} - #{booking.zip} #{booking.city}"%></p>
          <p><strong>Vos options:</strong>
            <% booking.items.each do |item|%>
              <%= item.name%>
              <%= item.price%>
            <% end %>
            <p><strong>Prix total:</strong> CHF <%= booking.price%>.-</p>
            <div class="row justify-content-center mt-3">
              <a href="#" class="btn-straight mx-2">Modifier</a>
              <a href="#" class="btn-straight mx-2">Annuler</a>
            </div>

          </div>
          <%# <% if booking.status == "pending" %>
          <%#<%= link_to "Cancel booking", booking_path(booking), data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-primary" %>
          <%# <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container-fluid" data-controller="loading" data-action="submit->loading#launchAnimation">
  <div data-loading-target="page">
    <div class="container">
      <h2 class="text-shadow mt-3" Style="font-size: 3rem">RESERVATION</h2>
    </div>
    <div class="container">
      <div class="container text-center">
        <p>Sélectionnez les dates qui vous intéressent</p>
      </div>
      <div class="reservation-card col-lg-8 p-4 mx-auto">
        <%= simple_form_for @booking do |f|%>
          <%= f.input :date, as: :string,
          wrapper_html: {class: "mb-4"},
          input_html: {data: {controller: "flatpickr"}}
        %>
          <%= f.input :street, label: "Rue" %>
          <%= f.input :city, label: "Ville"%>
          <%= f.input :zip, label: "NPA" %>
          <div class= "mb-2">
            <p>Sélectionnez les options qui vous intéressent</p>
            <%= f.collection_check_boxes :item_ids, @items, :id, :name do |b| %>
              <div>
                <%= b.check_box %>
                <%= b.label %>
              </div>
            <% end %>
          </div>
          <div class="container mb-4">
            <%= f.submit :Suivant, class: 'btn-straight'%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/paiement.html.erb
<div class= "container-fluid">
  <div class="m-3">
    <h2 class="text-shadow" style="font-size: 3rem"> PAIEMENT </h2>
  </div>
  <div class= "col-md-5 mx-auto">
    <div class="card-paiement col-md-12 d-flex flex-column align-items-center">
      <div class="col-12">
        <%= image_tag("cartedepaiement.jpg", class: "card-image") %>
      </div>
      <form class="col-lg-12">
        <div class="form-group">
          <label for="">Numéro de la carte</label>
          <input type="" class="form-control" placeholder="Veuillez entrer le numéro de la carte" value="4970 5698 2145 3658">
          <small class="form-text text-muted">Vos données restent confidentielles.</small>
        </div>
        <div class="form-group">
          <label for="">Titulaire de la carte</label>
          <input type="" class="form-control" placeholder="Titulaire de la carte", value="Julien de Lambilly">
        </div>
        <div class="form-row d-flex justify-content-between">
          <div class="form-group col-5 col-lg-5">
            <label for="">Date d'expiration </label>
            <input type="month" class="form-control" placeholder="Date d'expiration", value="2024-06">
          </div>
          <div class="form-group col-5 col-lg-5">
            <label for=""> CVV</label>
            <input type="" class="form-control" placeholder="CVV", value="520">
          </div>
        </div>
        <button data-controller="sweetalert" data-action="click->sweetalert#validation:prevent" data-sweetalert-id-value="<%= @observation_planning.id %>" class="btn-straight mt-3 mb-2">Confirmer le paiement</button>
        <div class="row text-center">
          <a href="#" style="color: black; font-size: 0.9rem">Retour</a>
        </div>
      </form>
    </div>
  </div>
</div>