config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/mes-réservations", to: "bookings#index", as: :mes_reservations
  get "/bookings/:id/checkout/paiement", to: "bookings#paiement", as: :paiement
  get "users/dashboard", to: "pages#dashboard"
  get "users/informations", to: "pages#informations"
  resources :bookings, only: %i[new create show] do
    member do
      get :checkout
    end
  end
  get "/objects", to: "celestial_bodies#index", as: :objects

  resources :observation_plannings, only: %i[index show]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-md navbar-dark navbar-skyeasy">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "Logo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-sharp fa-solid fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <%#<%= image_tag "logo user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <li class="nav-item active">
            <%= link_to "Mes réservations", mes_reservations_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mes informations", users_informations_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mes plannings d'observation", observation_plannings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link", style: 'color: white' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>