config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/mes-réservations", to: "bookings#index", as: :mes_reservations
  get "/bookings/:id/checkout/paiement", to: "bookings#paiement", as: :paiement
  get "users/dashboard", to: "pages#dashboard"
  get "users/informations", to: "pages#informations"
  resources :bookings, only: %i[new create show] do
    member do
      get :checkout
    end
  end
  get "/objects", to: "celestial_bodies#index", as: :objects

  resources :observation_plannings, only: %i[index show]
end

app/views/pages/dashboard.html.erb
<div class="container mt-4">
  <div class="row text-center">
    <p class="text-shadow" style="font-size: 2rem"> <%= "#{current_user.first_name} #{current_user.last_name}" %> </p>
  </div>
  <div class="col-sm-6 offset-sm-3 text-center">
    <div class="row">
      <%= link_to "Mes informations", users_informations_path %>
    </div>
    <div class="row mb-4">
      <%= link_to "Mes réservations", mes_reservations_path, style:'color: white' %>
    </div>
    <div class="row">
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, style: 'color:white' %>
    </div>
  </div>
</div>
</div>

app/views/pages/home.html.erb
  <div class="container-fluid home-header">
    <div class="home-header-title">
      <h1 class="text-shadow" style="text-align: center">EASYSKY</h1>
      <h2 style="font-size: 1.60rem">Explorez le ciel depuis chez vous</h2>
    </div>

    <section>
      <div class="home-header-moon">
      </div>
      <div class="home-header-link">
        <%= link_to "Découvrir", objects_path, class:"text-shadow", style:"color: white; font-size: 1.5rem"%>
      </div>
    </section>

    <div class="row justify-content-center" style="text-align: center">
      <div class="col-md-6 offset-md-3" style="margin-left: 0px">
        <%= link_to "Réserver", new_booking_path, class:"btn-straight", style:"padding-right: 55px; padding-left: 55px; font-size: 1.5rem" %>
      </div>
    </div>

  </div>
  <div class="home-info">
    <div class="home-info-section">
      <div class="container">
        <h2 class="text-shadow" style="color: white" >Technologie</h2>
        <div class="row justify-content-center m-4">
          <%= image_tag "telescope_unistellar.png", alt: "telescope", style: 'max-width:60%'%>
        </div>
        <p style="color: white">La pollution lumineuse affecte la qualité des images astronomiques et rend les objets célestes invisibles à l'œil nu. Les télescopes que nous utilisons atténuent efficacement l'impact de la pollution lumineuse, permettant une observation claire des objets lointains, même en milieu urbain. Ils reconnaissent instantanément les objets dans le champ de vision, ne nécessitant pas de connaissance préalable des constellations ou de l'orientation vers l'étoile polaire. Les télescopes offrent une expérience d'observation précise et facile pour les passionnés d'astronomie débutants ou expérimentés, peu importe où ils se trouvent.</p>
      </div>
    </div>
    <div class="home-info-section">
      <div class="container">
        <h2 class="text-shadow" style="color: white" >Explorer</h2>
        <div class="row justify-content-center m-4">
          <%= image_tag "galaxy.png", alt: "Planet", style: 'max-width:60%' %>
        </div>
        <p style="color: white">Le télescope est facile à utiliser et vous n'avez pas besoin de connaissances préalables en astronomie pour profiter de cette expérience unique. Les instructions sont claires et simples à suivre, et vous pouvez piloter le télescope avec votre smartphone ou tablette. Vous pourrez voir de vos propres yeux les différentes formes et couleurs des galaxies et des nébuleuses, ainsi que découvrir les caractéristiques uniques de chaque planète. Cette expérience peut être enrichissante pour les enfants et les adultes qui souhaitent en apprendre davantage sur l'espace. Plongez dans l'aventure de l'exploration spatiale depuis chez vous !</p>
      </div>
    </div>
    <div class="home-info-section">
      <div class="container">
        <h2 class="text-shadow" style="color: white" >Réserver un télescope</h2>
        <div class="row justify-content-center m-4">
          <%= image_tag "observer.png", alt: "telescope", style: 'max-width:80%'%>
        </div>
        <p style="color: white">EasySky offre un service de location de télescopes pour que vous puissiez observer les merveilles de l'univers depuis chez vous. Nous apportons les étoiles jusqu'à vous, sans avoir besoin de voyager vers des endroits isolés ou de dépenser une fortune pour acheter votre propre télescope. Nous fournissons également des instructions claires et simples à suivre pour que vous puissiez profiter pleinement de votre expérience d'observation céleste. Avec notre service de location de télescopes, vous pouvez observer les étoiles depuis votre propre cour, balcon ou terrasse. C'est une expérience unique et passionnante que vous pouvez partager avec votre famille et vos amis. Réservez votre télescope sans attendre ! </p>
      </div>
    </div>
    <div class="home-info-section">
      <div class="container">
        <h2 class="text-shadow" style="color: white" >Partager</h2>
        <div class="row justify-content-center m-4">
          <%= image_tag "family.png", alt: "family", style: 'max-width:60%' %>
        </div>
        <p style="color: white">Nous vous offrons une expérience d'observation céleste incroyable à partager avec vos proches, que vous soyez chez vous ou en déplacement. Vous pouvez passer une soirée à contempler les constellations, repérer les planètes et discuter de la vie dans l'univers. Cette activité est une excellente occasion de se rapprocher et de se reconnecter avec les gens qui comptent pour vous et de créer des souvenirs inoubliables. Invitez vos amis et votre famille à découvrir les merveilles de l'univers avec vous.</p>
      </div>
    </div>
  </div>
  <div class="home-footer" style="text-align: center">
    <button type="button" class="col-4 btn-straight">Contactez-Nous!</button>
  </div>

app/views/pages/informations.html.erb
<div class="container-fluid">
  <div class="container mt-4 mb-4">
    <h2 class="text-shadow" style="font-size: 3rem">MES INFORMATIONS</h2>
  </div>

  <div class="container-fluid">
    <div class="checkout-card col-lg-8 mx-auto">
      <div class="d-flex flex-column mb-2 justify-content-between">
          <p><strong>Nom: </strong></p>
          <p> <%= current_user.last_name %></p>
      </div>

      <div class="d-flex flex-column mb-2 justify-content-between">
          <p><strong>Prénom: </strong></p>
          <p> <%= current_user.first_name %></p>
      </div>

      <div class="d-flex flex-column mb-2 ">
          <p><strong>Mail: </strong></p>
          <p> <%= current_user.email %></p>
      </div>

      <div class="d-flex flex-column">
        <p><strong>Adresse: </strong></p>
        <p> <%= "#{current_user.street} #{current_user.zip}  #{current_user.city}" %></p>
      </div>

      <div class="row justify-content-center mt-3">
        <div class="row justify-content-center">
          <a href="#" class="btn-straight mx-1 my-2 px-3">Editer mes informations</a>
        </div>

        <div class="row justify-content-center">
          <a href="#" class="btn-straight mx-1 my-2 px-3">Supprimer mon compte</a>
        </div>
      </div>
    </div>
  </div>
</div>